apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose-resolved.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jicofo
  name: jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jicofo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose-resolved.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: jicofo
    spec:
      containers:
        - env:
            - name: JIBRI_BREWERY_MUC
              value: jibribrewery
            - name: JIBRI_PENDING_TIMEOUT
              value: "90"
            - name: JICOFO_AUTH_PASSWORD
              value: 1769218a7b570038f902dfb0ffba40fe
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_COMPONENT_SECRET
              value: 5520fef605cf27cfc08451b0bae4b1fe
            - name: JIGASI_BREWERY_MUC
              value: jigasibrewery
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: UTC
            - name: XMPP_AUTH_DOMAIN
              value: auth.rars-j
            - name: XMPP_DOMAIN
              value: rars-j
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.rars-j
            - name: XMPP_SERVER
              value: prosody
          image: jitsi/jicofo:stable-4857
          name: jicofo
          resources: {}
      restartPolicy: Always
status: {}
